fragment FSensorBase on SensorNodeType {
  id
  name
  favorite
  isCritical
  isOnline
  unitType: unitTypeStr
  currentValue
  values {
    startDate
    average: avgValue
  }
  category: mainframe {
    id
  }
}
