fragment FTriggerGroup on ThresholdGroupActuatorType {
  group: thresholdGroup {
    ...FGroupBase
    actuatorConditions {
      ...FActuatorConditionBase
    }
    sensorConditions {
      ...FSensorConditionBase
    }
  }
  priority
  changeToState
}
