mutation MRemoveSensorCondition($sensorConditionId: Int!) {
  result: removeSensorCondition(sensorConditionId: $sensorConditionId) {
    group: thresholdGroup {
      sensorConditions {
        ...FSensorCondition
      }
    }
  }
}
