mutation MRemoveActuatorCondition($actuatorConditionId: Int!) {
  result: removeActuatorCondition(actuatorConditionId: $actuatorConditionId) {
    group: thresholdGroup {
      actuatorConditions {
        ...FActuatorCondition
      }
    }
  }
}
