query QActuatorDetail($actuatorId: Int!) {
  actuator: actuatorNode(id: $actuatorId) {
    id
    currentState
    batteryLevel
    isOnline
    manualOverride
    manualOverrideValue

    groups: thresholdGroupActuators {
      ...FTriggerGroup
    }
  }
}
