query QSensorHistoricalValues(
  $sensorId: Int!
  $endDatetime: DateTime
  $dateRangeType: DateRangeTypeEnum
) {
  data: sensorValuesForDateRange(
    sensorId: $sensorId
    endDatetime: $endDatetime
    dateRangeType: $dateRangeType
  ) {
    minValue
    maxValue
    values {
      startDate
      max: maxValue
      min: minValue
      average: avgValue
    }
  }
}
