query QSensorDetail($sensorId: Int!) {
  sensor: sensorNode(id: $sensorId) {
    id
    currentValue
    batteryLevel
    isOnline
    unitType

    # criticalOver
    # criticalUnder
    # optimalValue
  }
}
