subscription SValues {
  change: nodeValues {
    type
    data {
      ... on SensorNodeSubscriptionType {
        id
        currentValue
        isCritical
      }
      ... on ActuatorNodeSubscriptionType {
        id
        currentState
      }
    }
  }
}
