subscription SValues {
  change: nodeValues {
    type
    data {
      ... on SensorNodeSubscriptionType {
        id
        currentValue
      }
      ... on ActuatorNodeSubscriptionType {
        id
        currentState
        isOnline
      }
      ... on NotificationsUnreadCountType {
        unreadCount
      }
    }
  }
}
